from . import retenue_source_type
from . import res_company
from . import res_config_settings
from . import res_partner
from . import account_journal
from . import account_tax
from . import account_payment
from . import account_move
from . import retenu_source_record
